jira_issues_fields:
  - name: id
    type: VARCHAR(50)
    source: id
  - name: issue_key
    type: VARCHAR(50)
    source: key
  - name: summary
    type: TEXT
    source: fields.summary
  - name: issuetype_id
    type: VARCHAR(50)
    source: fields.issuetype.id
  - name: issuetype_name
    type: VARCHAR(50)
    source: fields.issuetype.name
  - name: issuetype_subtask
    type: BOOLEAN
    source: fields.issuetype.subtask
  - name: created
    type: TIMESTAMP
    source: fields.created
  - name: resolutiondate
    type: TIMESTAMP
    source: fields.resolutiondate
  - name: project_id
    type: VARCHAR(50)
    source: fields.project.id
  - name: project_key
    type: VARCHAR(50)
    source: fields.project.key
  - name: project_name
    type: VARCHAR(100)
    source: fields.project.name
  - name: project_type_key
    type: VARCHAR(50)
    source: fields.project.projectTypeKey
  - name: assignee_email
    type: VARCHAR(100)
    source: fields.assignee.emailAddress
  - name: assignee_name
    type: VARCHAR(100)
    source: fields.assignee.displayName
  - name: priority_name
    type: VARCHAR(50)
    source: fields.priority.name
  - name: priority_id
    type: VARCHAR(50)
    source: fields.priority.id
  - name: updated
    type: TIMESTAMP
    source: fields.updated
  - name: status_id
    type: VARCHAR(50)
    source: fields.status.id
  - name: status_name
    type: VARCHAR(50)
    source: fields.status.name
  - name: status_category_color
    type: VARCHAR(50)
    source: fields.status.statusCategory.colorName
  - name: sync_time
    type: TIMESTAMP
    source: constant.utcnow