services:
  # metabase
  #
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      - postgres-db
    ports:
      - 3000:3000
    environment:
      #MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mypassword
      MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - data-ops-network
################################ Networks ############################################
networks:
  data-ops-network:
    external: true # Use the existing network from docker-compose.yml

################################ Volumes ############################################
