services:
  ############################################################################
  # pgadmin
  #
  pgadmin:
    #image: dpage/pgadmin4:8.7 # https://hub.docker.com/layers/dpage/pgadmin4/8.7/images/sha256-198236db5d90e491354c351ccd02a21ce736030b72cd0f8b05430bc48a59d86b?context=explore
    image: dpage/pgadmin4:8.14.0 # https://hub.docker.com/r/dpage/pgadmin4/tags
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    depends_on:
      - postgres-db
    networks:
      - data-ops-network
  ############################## 1.3 MongoDB Community Edition Database #############################################
  #
  mongo-db-community-server:
    build:
      context: ./01-databases/02-mongodb-community-server
      dockerfile: Dockerfile
    container_name: mongo-db-community-server
    ports:
      - "27017:27017"
    #env_file: ./databases/02-mongodb-community-server/.env
    env_file:
      - .env
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db-community-server-volume:/data/db
    networks:
      - data-ops-network
volumes:
  pgadmin-volume:
    name: pgadmin-volume
  mongo-db-community-server-volume:
    driver: local