############################## Data Warehouse ##############################################
services:
  # clickhouse-server
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.8.7.41
    container_name: clickhouse-server
    ports:
      - "9000:9000" # Native TCP protocol
      - "8123:8123" # HTTP interface (for Tabix, curl, etc.)
      - "9009:9009" # Interserver HTTP communication
      - "9181:9181" # Keeper (ZooKeeper-compatible protocol)
    restart: always
    volumes:
      - ./04-warehouse/01-clickhouse/config/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./04-warehouse/01-clickhouse/users/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./04-warehouse/01-clickhouse/clickhouse-logs:/var/log/clickhouse-server/
      - clickhouse-server-data:/var/lib/clickhouse/
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"] # Simple query to check server responsiveness
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data-ops-network
  # tabix
  clickhouse-tabix-web-client:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: clickhouse-tabix-web-client
    ports:
      - "8090:80"
    restart: always
    depends_on:
      - clickhouse-server
    environment:
      - CH_HOST=clickhouse-server
      - CH_PORT=8123
    networks:
      - data-ops-network

################################ Networks ############################################
networks:
  data-ops-network:
    external: true # Use the existing network from docker-compose.yml

################################ Volumes ############################################
volumes:
  clickhouse-server-data:
    name: clickhouse-server-data
