# dagster_pipeline/definitions.py
"""
Simplified definitions using factory pattern.
Much less boilerplate!
"""

import os
from typing import Dict, Any, Optional
from dagster import Definitions, ScheduleDefinition, load_assets_from_modules, AssetMaterialization

# Resources
from dagster_pipeline.resources.databases import (
    MySQLResource,
    ClickHouseResource,
    PostgreSQLResource,
)
from dagster_pipeline.utils.schema_loader import SchemaLoader

# Assets (all generated by factory)
from dagster_pipeline.assets.etl import mysql_to_clickhouse
from dagster_pipeline.assets.etl import mysql_to_mysql
from dagster_pipeline.assets.etl import mysql_agg_to_mysql
from dagster_pipeline.assets.data_migration import lead_migration  # NEW: For lead migration assets

# ============================================================================
# RESOURCES
# ============================================================================

def build_resources() -> Dict[str, Optional[Any]]:
    """Build resources conditionally based on env vars."""
    config_base_path = os.getenv("SCHEMA_CONFIG_PATH", "/app/dagster_pipeline/config")
    
    resources = {
        "sc_mysql_amtdb_resource": MySQLResource(
            host=os.getenv("SC_AMT_REPLICA_MYSQL_DB_HOST"),
            port=int(os.getenv("MYSQL_DB_PORT", 3306)),
            user=os.getenv("MYSQL_AMT_DB_USER"),
            password=os.getenv("MYSQL_AMT_DB_PASSWORD", ""),
        ) if all(os.getenv(k) for k in ["SC_AMT_REPLICA_MYSQL_DB_HOST", "MYSQL_AMT_DB_USER"]) else None,
        
        "sc_mysql_sales_service_dev_resource": MySQLResource(
            host=os.getenv("SC_SALES_SERVICE_DEV_MYSQL_DB_HOST"),
            port=int(os.getenv("MYSQL_DB_PORT", 3306)),
            user=os.getenv("SC_SALES_SERVICE_DEV_MYSQL_DB_USER"),
            password=os.getenv("SC_SALES_SERVICE_DEV_MYSQL_DB_PASSWORD", ""),
        ) if all(os.getenv(k) for k in ["SC_SALES_SERVICE_DEV_MYSQL_DB_HOST", "SC_SALES_SERVICE_DEV_MYSQL_DB_USER"]) else None,
        
        "dagster_postgres_resource": PostgreSQLResource(
            host=os.getenv("PG_DAGSTER_HOST"),
            port=int(os.getenv("DAGSTER_PG_DB_PORT", 5432)),
            user=os.getenv("PG_DAGSTER_USER"),
            password=os.getenv("PG_DAGSTER_PASSWORD", ""),
        ) if all(os.getenv(k) for k in ["PG_DAGSTER_HOST", "PG_DAGSTER_USER"]) else None,
        
        "clickhouse_resource": ClickHouseResource(
            host=os.getenv("SC_CH_DB_HOST"),
            port=int(os.getenv("SC_CH_DB_PORT", 8443)),
            user=os.getenv("SC_CH_DB_USER"),
            password=os.getenv("SC_CH_DB_PASSWORD", ""),
            secure=os.getenv("CLICKHOUSE_SECURE", "True").lower() == "true",
        ) if all(os.getenv(k) for k in ["SC_CH_DB_HOST", "SC_CH_DB_USER"]) else None,
        
        "schema_loader": SchemaLoader(config_base_path=config_base_path),
    }
    
    # Log missing resources
    missing = {k: v for k, v in resources.items() if v is None}
    if missing:
        print(f"Warning: Missing resources: {list(missing.keys())}")
    
    return resources

all_resources = build_resources()

# ============================================================================
# SCHEDULES
# ============================================================================

# Example schedule (uncomment/adjust)
# mysql_to_clickhouse_schedule = ScheduleDefinition(
#     job="mysql_to_clickhouse_job",  # Define a job wrapping assets
#     cron_schedule="0/15 6-21 * * *",
#     execution_timezone="UTC",
# )

# ============================================================================
# LOAD ALL ASSETS
# ============================================================================

try:
    all_assets = load_assets_from_modules([mysql_to_clickhouse, mysql_to_mysql, mysql_agg_to_mysql, lead_migration])  # UPDATED: Added lead_migration
    print(f"Loaded {len(all_assets)} assets.")
except Exception as e:
    print(f"Error loading assets: {e}")
    all_assets = []

# ============================================================================
# DEFINITIONS
# ============================================================================

# Key Fix: Alias generics to specifics
aliased_resources = {
    **all_resources,
    "source_mysql_resource": all_resources["sc_mysql_amtdb_resource"],  # For MySQL factory source
    "target_mysql_resource": all_resources["sc_mysql_sales_service_dev_resource"],  # For MySQL factory target (adjust if staging)
    "mysql_resource": all_resources["sc_mysql_amtdb_resource"],  # For ClickHouse factory source
    # Add "postgres_resource" alias if using Postgres sources
    # NEW: No extra aliases needed for lead migration factory (reuses MySQL ones)
}

defs = Definitions(
    assets=all_assets,
    # schedules=[mysql_to_clickhouse_schedule],
    resources=aliased_resources,
)