# dagster_pipeline/definitions.py
"""
Simplified definitions using factory pattern
Much less boilerplate!
"""

import os
from dagster import Definitions, ScheduleDefinition, load_assets_from_modules

# Resources
from dagster_pipeline.resources.databases.v1.databases import (
    MySQLResource,
    ClickHouseResource,
    PostgreSQLResource,
)
from dagster_pipeline.resources.schema_loader.v1.schema_loader import SchemaLoader

# Assets (all generated by factory)
from dagster_pipeline.assets.etl import mysql_to_clickhouse

# ============================================================================
# RESOURCES
# ============================================================================

all_resources = {
    "mysql_resource": MySQLResource(
        host=os.getenv("SC_AMT_REPLICA_MYSQL_DB_HOST"),
        port=int(os.getenv("MYSQL_DB_PORT", 3306)),
        user=os.getenv("MYSQL_AMT_DB_USER"),
        password=os.getenv("MYSQL_AMT_DB_PASSWORD", "")
    ) if all(os.getenv(k) for k in ["SC_AMT_REPLICA_MYSQL_DB_HOST", "MYSQL_AMT_DB_USER"]) else None,
    
    # Dagster's internal Postgres (for state management in kvs table)
    "dagster_postgres_resource": PostgreSQLResource(
        host=os.getenv("PG_DAGSTER_HOST"),
        port=int(os.getenv("DAGSTER_PG_DB_PORT", 5432)),
        user=os.getenv("PG_DAGSTER_USER"),
        password=os.getenv("PG_DAGSTER_PASSWORD", "")
    ) if all(os.getenv(k) for k in ["PG_DAGSTER_HOST", "PG_DAGSTER_USER"]) else None,
    
    # Postgres data source (for ETL)
    "postgres_resource": PostgreSQLResource(
        host=os.getenv("SC_POSTGRES_DB_HOST"),
        port=int(os.getenv("POSTGRES_DB_PORT", 5432)),
        user=os.getenv("POSTGRES_DB_USER"),
        password=os.getenv("POSTGRES_DB_PASSWORD")
    ) if all(os.getenv(k) for k in ["SC_POSTGRES_DB_HOST", "POSTGRES_DB_USER"]) else None,
    
    "clickhouse_resource": ClickHouseResource(
        host=os.getenv("SC_CH_DB_HOST"),
        port=int(os.getenv("SC_CH_DB_PORT", 8443)),
        user=os.getenv("SC_CH_DB_USER"),
        password=os.getenv("SC_CH_DB_PASSWORD", ""),
        secure=os.getenv("CLICKHOUSE_SECURE", "True").lower() == "true"
    ) if all(os.getenv(k) for k in ["SC_CH_DB_HOST", "SC_CH_DB_USER"]) else None,
    
    "schema_loader": SchemaLoader(config_base_path="/app/dagster_pipeline/config")
}

# ============================================================================
# SCHEDULES
# ============================================================================

# MySQL → ClickHouse schedule (every 15 minutes between 6 AM - 9 PM UTC)
"""mysql_to_clickhouse_schedule = ScheduleDefinition(
    job_name="mysql_to_clickhouse_job",
    cron_schedule="*/15 6-21 * * *",
    execution_timezone="UTC"
)"""

# ============================================================================
# LOAD ALL ASSETS
# ============================================================================

# Load all assets from the factory (no manual import of individual assets!)
all_assets = load_assets_from_modules([mysql_to_clickhouse])

# ============================================================================
# DEFINITIONS
# ============================================================================

defs = Definitions(
    assets=all_assets,
    #schedules=[mysql_to_clickhouse_schedule],
    resources=all_resources,
)