#FROM confluentinc/cp-kafka:latest
FROM confluentinc/cp-kafka:7.6.1

# Add custom configuration or tools if needed
# Example: Copying custom Kafka server properties
# COPY custom-server.properties /etc/kafka/server.properties