CREATE TABLE IF NOT EXISTS call_records
(
    call_key String,
    call_id String,
    is_answered Nullable(UInt8),
    is_assigned Nullable(UInt8),
    is_abandoned Nullable(UInt8),
    queue_date Nullable(DateTime),
    call_date Nullable(DateTime),
    talk_date Nullable(DateTime),
    hangup_date Nullable(DateTime),
    wait_duration Nullable(Int32),
    duration Nullable(Int32),
    is_short_call Nullable(UInt8),
    caller_id Nullable(String),
    called_number Nullable(String),
    queue_name Nullable(String),
    is_inbound Nullable(UInt8),
    agent_name Nullable(String),
    agent_email Nullable(String),
    hold_duration Nullable(Int32),
    has_voicemail Nullable(UInt8),
    unique_id Nullable(String),
    local_release Nullable(UInt8),
    answered_by Nullable(String),
    status Nullable(String),
    wrapup_code Nullable(String),
    voicemail_duration Nullable(Int32),
    disposition Nullable(String),
    has_csat Nullable(UInt8),
    csat_score Nullable(Int32),
    csat_completed Nullable(UInt8),
    csat_answers Nullable(String),
    csat Nullable(UInt8),
    black_list Nullable(UInt8),
    source_tenant Nullable(String),
    hangup_cause Nullable(String),
    transferred Nullable(UInt8),
    attendant_overflow Nullable(UInt8),
    campaign_name Nullable(String),
    channel Nullable(String),
    is_click2call Nullable(UInt8),
    is_ivr_click2call Nullable(UInt8),
    sync_time DateTime
)
ENGINE = ReplacingMergeTree()
ORDER BY (call_id, sync_time)