# Use the official MySQL image as the base image
FROM mysql:latest
LABEL authors="Rodgers Nyangweso"

# Set the default environment variables (customize as needed)
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=my_database
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Expose the default MySQL port
EXPOSE 3306